# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_1.0_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=1.0 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.9_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.9 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.7_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.7 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.6_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.6 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.5_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.5 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.4_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.4 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.3_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.3 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.2_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.2 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.1_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=3 --maskTh=0.1 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.8_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.8 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_1.0_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=1.0 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.9_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.9 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.7_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.7 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.6_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.6 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.5_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.5 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.4_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.4 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.3_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.3 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.2_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.2 --kshot=4 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.1_2prompts_new_val_ratio_0_fewshot4 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.1 --kshot=4 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.9_2prompts_new_val_ratio_0_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.9 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.7_2prompts_new_val_ratio_0_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.7 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.6_2prompts_new_val_ratio_0_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.6 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.9_2prompts_new_val_ratio_0_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.9 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.7_2prompts_new_val_ratio_0_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.7 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.6_2prompts_new_val_ratio_0_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.6 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.9_2prompts_new_val_ratio_0_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.9 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.7_2prompts_new_val_ratio_0_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.7 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.6_2prompts_new_val_ratio_0_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0 --maskPlan=4 --maskTh=0.6 --kshot=4 --headClass=3 --wandb;
#
# brca 4  全部存档
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.9_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.9 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.7_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.7 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.6_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.6 --kshot=4 --headClass=2 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.9_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.9 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.7_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.7 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.6_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.6 --kshot=4 --headClass=2 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.9_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.9 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.7_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.7 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.6_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.6 --kshot=4 --headClass=2 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.9_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.9 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.7_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.7 --kshot=4 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.6_2prompts_new_val_ratio_0.25_fewshot4_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.6 --kshot=4 --headClass=2 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.9_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.9 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.7_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.7 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.6_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.6 --kshot=4 --headClass=3 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.9_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.9 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.7_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.7 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.6_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.6 --kshot=4 --headClass=3 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.9_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.9 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.7_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.7 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.6_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.6 --kshot=4 --headClass=3 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.9_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.9 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.7_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.7 --kshot=4 --headClass=3 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.6_2prompts_new_val_ratio_0.25_fewshot4_head3 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.6 --kshot=4 --headClass=3 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.9_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.9 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.7_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.7 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.6_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.6 --kshot=4 --headClass=1 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.9_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.9 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.7_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.7 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_3_0.6_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=3 --maskTh=0.6 --kshot=4 --headClass=1 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.9_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.9 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.7_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.7 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_4_0.6_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=4 --maskTh=0.6 --kshot=4 --headClass=1 --wandb;
#
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.9_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.9 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.7_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.7 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_1_0.6_2prompts_new_val_ratio_0.25_fewshot4_head1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=1 --maskTh=0.6 --kshot=4 --headClass=1 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.9_2prompts_new_val_ratio_0.25_fewshot16_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.9 --kshot=16 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.7_2prompts_new_val_ratio_0.25_fewshot16_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.7 --kshot=16 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --tcga_sub=brca --dataset_root=/data/shihuazhan/conch_features/brca --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_brca_conch_l3_l1_xt_xP_2_0.6_2prompts_new_val_ratio_0.25_fewshot16_head2 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.6 --kshot=16 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data2/shihuazhan/dataset/tcga_nsclc/conch --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_tcga_conch_l3_l1_xt_xP_2_0.9_2prompts_new_val_ratio_0.25_fewshot16_head2 --model=conch --seed=2023 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.9 --kshot=16 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data2/shihuazhan/dataset/tcga_nsclc/conch --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_tcga_conch_l3_l1_xt_xP_2_0.7_2prompts_new_val_ratio_0.25_fewshot16_head2 --model=conch --seed=2023 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.7 --kshot=16 --headClass=2 --wandb;
# CUDA_VISIBLE_DEVICES=2 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data2/shihuazhan/dataset/tcga_nsclc/conch --model_path=/data3/shihuazhan/output_wsi/ --cv_fold=5 --title=conch_tcga_conch_l3_l1_xt_xP_2_0.6_2prompts_new_val_ratio_0.25_fewshot16_head2 --model=conch --seed=2023 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_brca.yaml --val_ratio=0.25 --maskPlan=2 --maskTh=0.6 --kshot=16 --headClass=2 --wandb;
## 8
# CUDA_VISIBLE_DEVICES=0 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data2/zhangxiaoxian/tcga/plip --model_path=/data3/shihuazhan/output_wsi/ --num_splits=10 --use_split_files --split_dir=/data2/dongjiajun/code/xjh_few_shot_WSI_final/splits/tcga_nsclc/seed=1/splits10/8shots_10folds --cv_fold=5 --title=ablion_conch_0.2_tcga_8_plip_loss0.1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_tcga.yaml --maskPlan=2 --maskTh=0.2 --kshot=1004 --headClass=2 --loss_total=0.1 --wandb;
# CUDA_VISIBLE_DEVICES=0 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data2/zhangxiaoxian/tcga/plip --model_path=/data3/shihuazhan/output_wsi/ --num_splits=10 --use_split_files --split_dir=/data2/dongjiajun/code/xjh_few_shot_WSI_final/splits/tcga_nsclc/seed=1/splits10/4shots_10folds --cv_fold=5 --title=ablion_conch_0.2_tcga_4_plip_loss0.1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_tcga.yaml --maskPlan=2 --maskTh=0.2 --kshot=1004 --headClass=2 --loss_total=0.1 --wandb;
# CUDA_VISIBLE_DEVICES=0 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data2/zhangxiaoxian/tcga/plip --model_path=/data3/shihuazhan/output_wsi/ --num_splits=10 --use_split_files --split_dir=/data2/dongjiajun/code/xjh_few_shot_WSI_final/splits/tcga_nsclc/seed=1/splits10/16shots_10folds --cv_fold=5 --title=ablion_conch_0.1_tcga_16_plip_loss0.1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_tcga.yaml --maskPlan=2 --maskTh=0.1 --kshot=1004 --headClass=2 --loss_total=0.1 --wandb;


# /data/zhangxiaoxian/tcga/uni/
CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data/zhangxiaoxian/tcga/uni --model_path=/data3/shihuazhan/output_wsi/ --num_splits=10 --use_split_files --split_dir=/data2/dongjiajun/code/xjh_few_shot_WSI_final/splits/tcga_nsclc/seed=1/splits10/8shots_10folds --cv_fold=5 --title=ablion_conch_0.2_tcga_8_uni_loss0.1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_tcga.yaml --maskPlan=2 --maskTh=0.2 --kshot=1004 --headClass=2 --loss_total=0.1 --wandb;
CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data/zhangxiaoxian/tcga/uni --model_path=/data3/shihuazhan/output_wsi/ --num_splits=10 --use_split_files --split_dir=/data2/dongjiajun/code/xjh_few_shot_WSI_final/splits/tcga_nsclc/seed=1/splits10/4shots_10folds --cv_fold=5 --title=ablion_conch_0.2_tcga_4_uni_loss0.1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_tcga.yaml --maskPlan=2 --maskTh=0.2 --kshot=1004 --headClass=2 --loss_total=0.1 --wandb;
CUDA_VISIBLE_DEVICES=1 python3 main.py --project=mil_shz --datasets=tcga --dataset_root=/data/zhangxiaoxian/tcga/uni --model_path=/data3/shihuazhan/output_wsi/ --num_splits=10 --use_split_files --split_dir=/data2/dongjiajun/code/xjh_few_shot_WSI_final/splits/tcga_nsclc/seed=1/splits10/16shots_10folds --cv_fold=5 --title=ablion_conch_0.1_tcga_16_uni_loss0.1 --model=conch --seed=2021 --config=/home/shihuazhan/code/newWsi/prompt/config/IFMLE/cfg_tcga.yaml --maskPlan=2 --maskTh=0.1 --kshot=1004 --headClass=2 --loss_total=0.1 --wandb;
